[package]
name = "uni-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sep_ex1"
path = "src/09/ex1.rs"




[[bin]]
name = "oct1_ex1"
path = "src/10/01/ex1.rs"

[[bin]]
name = "oct1_ex2"
path = "src/10/01/ex2.rs"

[[bin]]
name = "oct1_ex3"
path = "src/10/01/ex3.rs"

[[bin]]
name = "oct1_ex4"
path = "src/10/01/ex4.rs"
[[bin]]
name = "oct1_ex5"
path = "src/10/01/ex5.rs"
[[bin]]
name = "oct1_ex6"
path = "src/10/01/ex6.rs"

[[bin]]
name = "oct2_ex1"
path = "src/10/02/ex1.rs"
[[bin]]
name = "oct2_ex2"
path = "src/10/02/ex2.rs"



[dependencies]
